// import DS from 'ember-data';

// export default DS.Model.extend({
// 	domain: DS.attr('string'),
// 	banned_by: DS.attr('string'),
// 	//media_embed: DS.attr('string'),
// 	subreddit: DS.attr('string'),
// 	//selftext_html: DS.attr('string'),
// 	likes: DS.attr('boolean'),
// 	//user_reports: DS.attr('string'),
// 	//secure_media: DS.attr('string'),
// 	link_flair_text: DS.attr('string'),
// 	id: DS.attr('string'),
// 	gilded: DS.attr('number'),
// 	//secure_media_embed: DS.attr('string'),
// 	clicked: DS.attr('boolean'),
// 	report_reasons: DS.attr('string'),
// 	author: DS.attr('string'),
// 	media: DS.attr('string'),
// 	score: DS.attr('number'),
// 	approved_by: DS.attr('string'),
// 	over_18: DS.attr('boolean'),
// 	hidden: DS.attr('boolean'),
// 	thumbnail: DS.attr('string'),
// 	subreddit_id: DS.attr('string'),
// 	edited: DS.attr('boolean'),
// 	link_flair_css_class: DS.attr('string'),
// 	author_flair_css_class: DS.attr('string'),
// 	downs: DS.attr('number'),
// 	//mod_reports: DS.attr('string'),
// 	saved: DS.attr('boolean'),
// 	is_self: DS.attr('boolean'),
// 	name: DS.attr('string'),
// 	permalink: DS.attr('string'),
// 	stickied: DS.attr('boolean'),
// 	created: DS.attr('date'),
// 	url: DS.attr('string'),
// 	author_flair_text: DS.attr('string'),
// 	title: DS.attr('string'),
// 	created_utc: DS.attr('date'),
// 	ups: DS.attr('number'),
// 	num_comments: DS.attr('number'),
// 	visited: DS.attr('boolean'),
// 	num_reports: DS.attr('number'),
// 	distinguished: DS.attr('boolean')
// });
